apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  DATABASE_URL: postgres://ecommerce:ecommerce123@postgres:5432/users_db?sslmode=disable
  REDIS_PASSWORD: redis123
